"use client"

import { motion } from "framer-motion"
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

type Props = {
  result: {
    asset: string
    recommendation: "BUY" | "HOLD" | "SELL"
    confidence: number
    time_horizon: string
  }
}

export default function DashboardResult({ result }: Props) {
  const barColor =
    result.recommendation === "BUY"
      ? "bg-buy"
      : result.recommendation === "SELL"
      ? "bg-sell"
      : "bg-hold"

  const textColor =
    result.recommendation === "BUY"
      ? "text-buy"
      : result.recommendation === "SELL"
      ? "text-sell"
      : "text-hold"

  return (
    <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
      <Card className="border-none shadow-2xl overflow-hidden bg-gradient-to-br from-card to-secondary/10">

        {/* TOP COLOR BAR */}
        <div className={`h-1.5 w-full ${barColor}`} />

        <CardHeader className="flex flex-col sm:flex-row justify-between gap-10 px-8 pt-10 pb-8">
          <div className="space-y-2">
            <Badge
              variant="outline"
              className="uppercase tracking-[0.25em] text-[10px]"
            >
              Primary Verdict
            </Badge>

            {/* ✅ TEXT COLOR ONLY */}
            <CardTitle
              className={`text-6xl md:text-7xl font-black ${textColor}`}
            >
              {result.recommendation}
            </CardTitle>
          </div>

          {/* CONFIDENCE */}
          <div className="bg-secondary/20 p-6 rounded-2xl border border-border/40 min-w-[220px]">
            <span className="uppercase text-[10px] text-muted-foreground">
              Oracle Confidence
            </span>

            <div className="flex items-center gap-4 mt-3">
              <span className="text-4xl font-black">
                {(result.confidence * 100).toFixed(0)}%
              </span>

              <div className="w-full h-2 bg-secondary rounded-full overflow-hidden">
                <motion.div
                  initial={{ width: 0 }}
                  animate={{ width: `${result.confidence * 100}%` }}
                  transition={{ duration: 1.2 }}
                  className="h-full bg-primary"
                />
              </div>
            </div>
          </div>
        </CardHeader>

        <CardContent className="px-8 pb-6">
          <div className="flex flex-wrap gap-4 items-center">
            <Badge variant="outline">Horizon: {result.time_horizon}</Badge>
            <Badge variant="outline">Asset: {result.asset}</Badge>
            <div className="flex-1 border-t border-dashed border-border" />
            <span className="text-xs text-muted-foreground italic">
              Generated by Oracle-v4 Multi-Agent System
            </span>
          </div>
        </CardContent>
      </Card>
    </motion.div>
  )
}
